
// ============================================================================
// SUI Move Contract - location_commitment.move
// ============================================================================

module location_addr::proximity {

    /// Represents a committed location with Poseidon hash commitment
    public struct LocationCommitment has key, store {
        id: UID,
        /// Poseidon hash commitment (32 bytes: single field element)
        /// C = Poseidon(x, y, z, blinding_factor)
        commitment: vector<u8>,
        /// Nonce counter to prevent replay attacks
        nonce: u64,
        /// Timestamp of creation
        created_at: u64,
        /// Owner address (SSU owner)
        owner: address,
    }

    /// Capability to update commitments (held by server)
    public struct ServerCap has key, store {
        id: UID,
    }

    /// Stores the Groth16 verifying key for proof verification
    public struct VerifyingKey has key, store {
        id: UID,
        /// Compressed verifying key bytes (328 bytes for BN254 with 2 public inputs)
        key_bytes: vector<u8>,
        /// Version/timestamp for key rotation support
        version: u64,
    }

    /// Event emitted when location commitment is created
    public struct CommitmentCreated has copy, drop {
        commitment_id: address,
        owner: address,
        timestamp: u64,
    }

    /// Event emitted when proximity proof is verified
    public struct ProximityVerified has copy, drop {
        commitment_id: address,
        verifier: address,
        nonce_used: u64,
    }

    /// Initialize module - creates server capability
    fun init(ctx: &mut TxContext) {
        let server_cap = ServerCap {
            id: object::new(ctx),
        };
        transfer::transfer(server_cap, tx_context::sender(ctx));
    }

    /// Initialize the verifying key (server-side only)
    public fun init_verifying_key(
        _cap: &ServerCap,
        key_bytes: vector<u8>,
        ctx: &mut TxContext
    ) {
        assert!(vector::length(&key_bytes) == 328, 6); // BN254 verifying key is 328 bytes (2 public inputs)
        
        let verifying_key = VerifyingKey {
            id: object::new(ctx),
            key_bytes,
            version: 1, // Initial version
        };

        transfer::share_object(verifying_key);
    }

    /// Create a new location commitment (server-side only)
    public fun create_commitment(
        _cap: &ServerCap,
        commitment_bytes: vector<u8>,
        owner: address,
        ctx: &mut TxContext
    ) {
        // Validate commitment format (must be 32 bytes for Poseidon hash)
        assert!(vector::length(&commitment_bytes) == 32, 1);
        
        let commitment = LocationCommitment {
            id: object::new(ctx),
            commitment: commitment_bytes,
            nonce: 0,
            created_at: tx_context::epoch(ctx),
            owner,
        };

        let commitment_id = object::uid_to_address(&commitment.id);
        
        sui::event::emit(CommitmentCreated {
            commitment_id,
            owner,
            timestamp: tx_context::epoch(ctx),
        });

        transfer::share_object(commitment);
    }

    /// Verify a proximity proof (public callable)
    /// Uses the canonical verifying key stored in the contract
    /// Validates that the proof is cryptographically correct for the given public inputs
    ///
    /// Security model:
    /// - The proof MUST be generated for THIS SPECIFIC commitment (binds proof to pre-published location)
    /// - Proof format and cryptographic validity are verified
    /// - Public inputs format (64 bytes: commitment_hash + max_distance_squared)
    /// - Proof verifies against CCP's canonical verifying key (ensures proof was generated by CCP)
    /// - The commitment_hash in public inputs MUST match the stored commitment (ties proof to specific SSU)
    ///
    /// The zkSNARK circuit verifies:
    /// - Poseidon commitment opening: C = Poseidon(x, y, z, blinding_factor)
    /// - Euclidean distance constraint: (x_p - x_t)² + (y_p - y_t)² + (z_p - z_t)² < max_distance²
    /// - Commitment hash matches the public input
    ///
    /// This ensures:
    /// 1. Player cannot prove proximity to arbitrary locations (must use pre-published commitment)
    /// 2. Server cannot generate proofs for different locations using same commitment object
    /// 3. Proof is bound to specific SSU location through commitment validation
    public fun verify_proximity_proof(
        commitment: &mut LocationCommitment,
        verifying_key: &VerifyingKey,
        proof_bytes: vector<u8>,
        public_inputs: vector<u8>,
        ctx: &mut TxContext
    ) {
        // Validate input sizes
        assert!(vector::length(&proof_bytes) >= 128, 2); // Groth16 proof is ~128 bytes
        assert!(vector::length(&public_inputs) == 64, 3); // Public inputs: commitment_hash (32), max_distance_squared (32)

        // CRITICAL SECURITY CHECK: Verify the commitment_hash in public inputs matches THIS commitment
        // This binds the proof to this specific pre-published location commitment
        // Without this check, a proof could be used with any commitment object
        verify_commitment_binding(&commitment.commitment, &public_inputs);

        // Verify the Groth16 proof cryptographically using canonical verifying key
        let valid = verify_groth16_proof_bn254(
            &verifying_key.key_bytes,
            &proof_bytes,
            &public_inputs
        );

        // Proof must be cryptographically valid
        assert!(valid, 4);

        // Increment nonce to prevent replay attacks
        commitment.nonce = commitment.nonce + 1;

        sui::event::emit(ProximityVerified {
            commitment_id: object::uid_to_address(&commitment.id),
            verifier: tx_context::sender(ctx),
            nonce_used: commitment.nonce - 1,
        });
    }

    /// Get commitment details
    public fun get_commitment(commitment: &LocationCommitment): vector<u8> {
        commitment.commitment
    }

    /// Get current nonce
    public fun get_nonce(commitment: &LocationCommitment): u64 {
        commitment.nonce
    }

    // ========================================================================
    // Internal verification functions
    // ========================================================================
    
    /// Verify that the commitment hash in public inputs matches the stored commitment
    /// This is the CRITICAL security binding that ties the proof to a specific location
    ///
    /// Security property: Ensures that a proof generated for commitment C cannot be used
    /// with a different commitment C'. This prevents:
    /// 1. Using a proof meant for one SSU location with a different SSU
    /// 2. Generating proofs for arbitrary locations and using them with any commitment
    /// 3. Proof shopping (trying a proof against multiple commitments until one works)
    fun verify_commitment_binding(
        stored_commitment: &vector<u8>,
        public_inputs: &vector<u8>
    ) {
        // Validate that public inputs are 64 bytes (commitment_hash + max_distance_squared)
        assert!(vector::length(public_inputs) == 64, 7);

        // Extract and verify the first 32 bytes (commitment_hash) match stored commitment
        // This is what makes the proof specific to THIS location commitment
        let mut i = 0;
        while (i < 32) {
            assert!(
                *vector::borrow(public_inputs, i) == *vector::borrow(stored_commitment, i),
                8 // Error: commitment hash mismatch - proof not for this location
            );
            i = i + 1;
        };
    }
    
    /// Verify Groth16 proof using BN254 curve
    /// This implements the proper Sui groth16 verification using stored verifying key
    fun verify_groth16_proof_bn254(
        verifying_key_bytes: &vector<u8>,
        proof_bytes: &vector<u8>,
        public_inputs: &vector<u8>
    ): bool {
        use sui::groth16::{Self, bn254};

        // Prepare the verifying key
        let pvk = groth16::prepare_verifying_key(&bn254(), verifying_key_bytes);
        let public_proof_inputs = groth16::public_proof_inputs_from_bytes(*public_inputs);
        let proof_points = groth16::proof_points_from_bytes(*proof_bytes);

        // Verify the proof cryptographically
        groth16::verify_groth16_proof(&bn254(), &pvk, &public_proof_inputs, &proof_points)
    }


    #[test_only]
    public fun init_for_testing(ctx: &mut TxContext) {
        init(ctx);
    }
}